name: CICD for Main Branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  test:
    name: Build and Test API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build API
        run: |
          docker build -t authors-api ./api
      - name: Test API
        run: |
          docker run -e CI=true authors-api npm run test
  deploy:
    needs: test
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
